# Generated by Django 5.0 on 2023-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='artist/covers/'),
        ),
    ]
