# Generated by Django 5.0 on 2023-12-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='followed_artist',
            new_name='follow_artist',
        ),
    ]
