# Generated by Django 5.0 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customer_follow_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followed_artists', to='user.artist'),
        ),
    ]
